<a href="https://colab.research.google.com/github/MichelleIhetu/BMEN-499_AlphaFold/blob/main/QA_Dataset_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
base_truth_dataset = [
{"Protein": "Betaamyloid", "Confidence Score(pLDDT)": 67.38, "Per-residue pLDDT":770, "Sequence Complexity (Amnio Acid Length)": 770, "Hydrophobicity":-0.58, "Binary Classification":"Disordered", "Net Charge": -0.08},
{"Protein": "Insulin", "Confidence Score(pLDDT)": 52.91, "Per-residue pLDDT": 110 , "Sequence Complexity (Amnio Acid Length)": 110 ,"Hydrophobicity" : 0.19 , "Binary Classification":"Disordered" , "Net Charge": -0.03},
{"Protein": "Myoglobin", "Confidence Score(pLDDT)": 97.19 , "Per-residue pLDDT": 154 , "Sequence Complexity (Amnio Acid Length)": 154 ,"Hydrophobicity" : -0.48 , "Binary Classification":"Ordered" , "Net Charge":0.01},
{"Protein": "Ubiquitin",  "Confidence Score(pLDDT)": 93.44, "Per-residue pLDDT": 229, "Sequence Complexity (Amnio Acid Length)": 229 ,"Hydrophobicity" : -0.48 , "Binary Classification": "Ordered" , "Net Charge": 0.00},
{"Protein" : "Calmodulin",  "Confidence Score(pLDDT)": 85.25, "Per-residue pLDDT": 149 , "Sequence Complexity (Amnio Acid Length)": 149 ,"Hydrophobicity" : -0.65, "Binary Classification": "Ordered" , "Net Charge": -0.16},
{"Protein" : "Thioredoxin", "Confidence Score(pLDDT)": 97.56, "Per-residue pLDDT": 105, "Sequence Complexity (Amnio Acid Length)": 105 ,"Hydrophobicity" : -0.10 , "Binary Classification": "Ordered" , "Net Charge": 0.05},
{"Protein": "Cytochrome",  "Confidence Score(pLDDT)": 97.94, "Per-residue pLDDT": 105 , "Sequence Complexity (Amnio Acid Length)": 105,"Hydrophobicity" : -0.71, "Binary Classification":"Ordered" , "Net Charge":0.09},
{"Protein": "Green Fluorescent Protein",  "Confidence Score(pLDDT)": 96.62 , "Per-residue pLDDT": 238 , "Sequence Complexity (Amnio Acid Length)": 234 ,"Hydrophobicity" : -0.52, "Binary Classification": "Ordered" , "Net Charge": -0.03},
{"Protein" : "Barnase", "Confidence Score(pLDDT)": 84.50, "Per-residue pLDDT": 157, "Sequence Complexity (Amnio Acid Length)": 157 ,"Hydrophobicity" : -0.34, "Binary Classification":"ordered", "Net Charge": 0.03},
{"Protein" : "Adenylate Kinase",  "Confidence Score(pLDDT)": None, "Per-residue pLDDT": None, "Sequence Complexity (Amnio Acid Length)": None,"Hydrophobicity" : None, "Binary Classification":"Ordered" , "Net Charge":0.03}
]

In [16]:
QA_dataset = [
{"Q1": "Is a disorder score above 0.5 a reliable cutoff for calling a region disordered?"},
{"Q2": " Do confidence scores drop for IDRs shorter than 10 residues?"},
{"Q3": "Do proline and glycine-rich regions consistently score higher disorder confidence than average?"},
{"Q4": "Does applying a sliding window smooth out confidence scores without losing true IDR signal?"},
{"Q5": "How far off are raw confidence scores from the true disorder rate in DisProt?"},
{"Q6": "When a confidence score falls in the uncertain range (0.4–0.6), does applying a sliding window smooth it toward the correct label, and what window size does the literature support?"},
{"Q7":"How much do raw confidence scores overestimate or underestimate true disorder rates across DisProt?"},
{"Q8": "After applying symbolic smoothing and isotonic calibration together, by how much does residue level F1 improve over raw scores, and is this improvement consistent with gains reported for similar post processing pipelines in the literature"},
{"Q9": "What is the MAE between raw disorder confidence scores and DisProt ground truth labels, and how many standard deviations (Z-score) away from the mean prediction is each incorrectly labeled residue?"},
{"Q10": "What is the MAE between raw disorder confidence scores and DisProt ground truth labels, and how many standard deviations (Z-score) away from the mean prediction is each incorrectly labeled residue?"}
]

In [17]:
ground_truth_answers = [
    {"A1": "A disorder score above 0.5 is generally considered a strong indicator of disorder, but a precise cutoff often requires experimental validation and depends on the specific protein and prediction method."},
    {"A2": "Confidence scores do tend to drop for IDRs shorter than 10 residues due to limited sequence context for prediction algorithms."},
    {"A3": "Proline and glycine-rich regions are often associated with disorder and can consistently score higher disorder confidence than average."},
    {"A4": "Applying a sliding window can smooth out confidence scores, and with an appropriate window size, it can reduce noise while preserving true IDR signals."},
    {"A5": "Raw confidence scores can deviate significantly from the true disorder rate in DisProt, often overestimating or underestimating disorder in certain contexts. Quantitative analysis like MAE is needed to determine the extent."},
    {"A6": "For confidence scores in the uncertain range (0.4–0.6), applying a sliding window can often smooth them towards the correct label. Literature suggests window sizes typically ranging from 3 to 9 residues for local smoothing."},
    {"A7": "Raw confidence scores can both overestimate and underestimate true disorder rates across DisProt, depending on the protein and region. The degree of overestimation/underestimation varies."},
    {"A8": "Applying symbolic smoothing and isotonic calibration together can significantly improve residue-level F1 scores over raw scores, with improvements consistent with other post-processing pipelines reported in the literature."},
    {"A9": "The MAE between raw disorder confidence scores and DisProt ground truth labels can be substantial. Incorrectly labeled residues can be several standard deviations (Z-score) away from the mean prediction, indicating significant discrepancies."},
    {"A10": "The MAE between raw disorder confidence scores and DisProt ground truth labels can be substantial. Incorrectly labeled residues can be several standard deviations (Z-score) away from the mean prediction, indicating significant discrepancies."}
]

In [18]:
import pandas as pd

base_truth_df = pd.DataFrame(base_truth_dataset)
print('Base Truth DataFrame Head:')
display(base_truth_df.head())

ground_truth_answers_df = pd.DataFrame(ground_truth_answers)
print('\nGround Truth Answers DataFrame Head:')
display(ground_truth_answers_df.head())

Base Truth DataFrame Head:

,Protein,Confidence Score(pLDDT),Per-residue pLDDT,Sequence Complexity (Amnio Acid Length),Hydrophobicity,Binary Classification,Net Charge
0,Betaamyloid,67.38,770.0,770.0,-0.58,Disordered,-0.08
1,Insulin,52.91,110.0,110.0,0.19,Disordered,-0.03
2,Myoglobin,97.19,154.0,154.0,-0.48,Ordered,0.01
3,Ubiquitin,93.44,229.0,229.0,-0.48,Ordered,0.00
4,Calmodulin,85.25,149.0,149.0,-0.65,Ordered,-0.16

Ground Truth Answers DataFrame Head:

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10
0,A disorder score above 0.5 is generally consid...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Confidence scores do tend to drop for IDRs sho...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Proline and glycine-rich regions are often ass...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Applying a sliding window can smooth out confi...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,Raw confidence scores can deviate significantl...,NaN,NaN,NaN,NaN,NaN

### Formatting Data for Evaluation

To effectively evaluate the performance using metrics like EM (Exact Match) and F1 scores, it's crucial to have the questions and their corresponding ground truth answers in a structured format. The current `ground_truth_answers_df` is sparse because each answer was placed in a separate dictionary within the list. Below, I'll create a unified DataFrame from the `QA_dataset` and `ground_truth_answers` lists, aligning each question with its correct answer.

In [19]:
# Extract questions from QA_dataset
questions = [list(q.values())[0] for q in QA_dataset]

# Extract ground truth answers from ground_truth_answers
ground_truth_answers_list = [list(a.values())[0] for a in ground_truth_answers]

# Create a DataFrame for evaluation
evaluation_df = pd.DataFrame({
    'Question': questions,
    'Ground_Truth_Answer': ground_truth_answers_list
})

print("Formatted Evaluation DataFrame Head:")
display(evaluation_df.head())
print("\nFormatted Evaluation DataFrame Info:")
display(evaluation_df.info())

Formatted Evaluation DataFrame Head:

,Question,Ground_Truth_Answer
0,Is a disorder score above 0.5 a reliable cutof...,A disorder score above 0.5 is generally consid...
1,Do confidence scores drop for IDRs shorter th...,Confidence scores do tend to drop for IDRs sho...
2,Do proline and glycine-rich regions consistent...,Proline and glycine-rich regions are often ass...
3,Does applying a sliding window smooth out conf...,Applying a sliding window can smooth out confi...
4,How far off are raw confidence scores from the...,Raw confidence scores can deviate significantl...

Formatted Evaluation DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Question             10 non-null     object
 1   Ground_Truth_Answer  10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

None

Now that the questions and ground truth answers are formatted for evaluation, you can provide your predicted answers. Once you have a list or DataFrame of predicted answers, I can help you calculate the EM and F1 scores by comparing them against the `Ground_Truth_Answer` column in `evaluation_df`.

In [20]:
# Placeholder for predicted answers. You would replace these with actual predictions from your model or analysis.
predicted_answers = [
    "A disorder score above 0.5 is often considered, but experimental validation is key.",
    "Yes, confidence scores generally drop for IDRs shorter than 10 residues due to limited context.",
    "Proline and glycine-rich regions frequently show higher disorder confidence.",
    "A sliding window can smooth scores, and with proper size, preserve IDR signals.",
    "Raw confidence scores can differ from DisProt truth; MAE analysis is needed to quantify.",
    "For uncertain range scores (0.4-0.6), a sliding window often smooths towards correctness, with literature suggesting 3-9 residue window sizes.",
    "Raw confidence scores can both overestimate and underestimate true disorder rates.",
    "Symbolic smoothing and isotonic calibration improve F1 scores, consistent with literature reports.",
    "MAE for raw scores can be significant. Incorrectly labeled residues may be several Z-scores from the mean.",
    "The MAE for raw disorder confidence scores against DisProt ground truth can be substantial, with incorrectly labeled residues often showing high Z-scores."
]

# Add the predicted answers to the evaluation DataFrame
evaluation_df['Predicted_Answer'] = predicted_answers

print("Evaluation DataFrame with Predicted Answers Head:")
display(evaluation_df.head())
print("\nEvaluation DataFrame Info:")
display(evaluation_df.info())

Evaluation DataFrame with Predicted Answers Head:

,Question,Ground_Truth_Answer,Predicted_Answer
0,Is a disorder score above 0.5 a reliable cutof...,A disorder score above 0.5 is generally consid...,A disorder score above 0.5 is often considered...
1,Do confidence scores drop for IDRs shorter th...,Confidence scores do tend to drop for IDRs sho...,"Yes, confidence scores generally drop for IDRs..."
2,Do proline and glycine-rich regions consistent...,Proline and glycine-rich regions are often ass...,Proline and glycine-rich regions frequently sh...
3,Does applying a sliding window smooth out conf...,Applying a sliding window can smooth out confi...,"A sliding window can smooth scores, and with p..."
4,How far off are raw confidence scores from the...,Raw confidence scores can deviate significantl...,Raw confidence scores can differ from DisProt ...

Evaluation DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Question             10 non-null     object
 1   Ground_Truth_Answer  10 non-null     object
 2   Predicted_Answer     10 non-null     object
dtypes: object(3)
memory usage: 372.0+ bytes

None

In [26]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [27]:
from collections import Counter
from nltk.translate.meteor_score import meteor_score

def calculate_f1(ground_truth, prediction):
    """Calculates F1 score based on token overlap."""
    ground_truth_tokens = nltk.word_tokenize(ground_truth.lower())
    prediction_tokens = nltk.word_tokenize(prediction.lower())

    common_tokens = Counter(ground_truth_tokens) & Counter(prediction_tokens)
    num_common = sum(common_tokens.values())

    if num_common == 0:
        return 0.0

    precision = num_common / len(prediction_tokens)
    recall = num_common / len(ground_truth_tokens)

    if (precision + recall) == 0:
        return 0.0

    f1 = (2 * precision * recall) / (precision + recall)
    return f1

def calculate_meteor(ground_truth, prediction):
    """Calculates METEOR score based on semantic similarity and recall."""
    # meteor_score expects reference as a list of tokens, and hypothesis as a list of tokens.
    # It can also take a list of reference translations.
    reference = [nltk.word_tokenize(ground_truth.lower())]
    hypothesis = nltk.word_tokenize(prediction.lower())
    return meteor_score(reference, hypothesis)

# Apply the functions to the DataFrame
evaluation_df['F1'] = evaluation_df.apply(lambda row: calculate_f1(row['Ground_Truth_Answer'], row['Predicted_Answer']), axis=1)
evaluation_df['METEOR'] = evaluation_df.apply(lambda row: calculate_meteor(row['Ground_Truth_Answer'], row['Predicted_Answer']), axis=1)

print("Evaluation DataFrame with F1 and METEOR Scores:")
display(evaluation_df.head())

overall_f1 = evaluation_df['F1'].mean()
overall_meteor = evaluation_df['METEOR'].mean()

print(f"\nOverall F1 Score: {overall_f1:.3f}")
print(f"Overall METEOR Score: {overall_meteor:.3f}")

Evaluation DataFrame with F1 and METEOR Scores:

,Question,Ground_Truth_Answer,Predicted_Answer,EM,F1,METEOR
0,Is a disorder score above 0.5 a reliable cutof...,A disorder score above 0.5 is generally consid...,A disorder score above 0.5 is often considered...,0,0.553191,0.357861
1,Do confidence scores drop for IDRs shorter th...,Confidence scores do tend to drop for IDRs sho...,"Yes, confidence scores generally drop for IDRs...",0,0.736842,0.652863
2,Do proline and glycine-rich regions consistent...,Proline and glycine-rich regions are often ass...,Proline and glycine-rich regions frequently sh...,0,0.551724,0.388035
3,Does applying a sliding window smooth out conf...,Applying a sliding window can smooth out confi...,"A sliding window can smooth scores, and with p...",0,0.651163,0.535221
4,How far off are raw confidence scores from the...,Raw confidence scores can deviate significantl...,Raw confidence scores can differ from DisProt ...,0,0.480000,0.335684

Overall F1 Score: 0.583
Overall METEOR Score: 0.449